use_frameworks!
platform :ios, '11.0'

target 'NotificationUserInfoModel_Example' do
  pod 'NotificationUserInfoModel', :path => '../'

  target 'NotificationUserInfoModel_Tests' do
    inherit! :search_paths

    
  end
end
